from __future__ import annotations

from .models import Product


PRODUCTS: list[Product] = [
    Product(
        id="sun-001",
        name="Aqua Shield UV Fluid SPF50+",
        brand="DermaVeil",
        category="sunscreen",
        price=168,
        benefits=["uv_protection", "lightweight", "anti_acne", "daily"],
        suitable_skin_types=["oily", "combination", "acne_prone", "sensitive"],
        avoid_for_skin_types=[],
        finish="natural",
        tags=["清爽", "通勤", "不搓泥"],
        hero_ingredients=["zinc oxide", "niacinamide", "centella"],
        free_from_ingredients=["fragrance", "alcohol_denat"],
        notes="偏轻薄水感，适合通勤和混油皮日常使用。",
    ),
    Product(
        id="sun-002",
        name="Barrier Moist Sun Cream SPF50+",
        brand="Skin Harbor",
        category="sunscreen",
        price=198,
        benefits=["uv_protection", "hydrating", "barrier_support", "daily"],
        suitable_skin_types=["dry", "sensitive", "normal"],
        avoid_for_skin_types=["oily"],
        finish="glowy",
        tags=["保湿", "敏感肌友好"],
        hero_ingredients=["ceramide", "panthenol", "squalane"],
        free_from_ingredients=["essential_oil"],
        notes="更适合干皮和屏障脆弱时期，妆前会更润。",
    ),
    Product(
        id="ser-001",
        name="Calm Balance Niacinamide Serum",
        brand="Novelle",
        category="serum",
        price=219,
        benefits=["brightening", "oil_control", "barrier_support", "anti_acne"],
        suitable_skin_types=["oily", "combination", "acne_prone", "normal"],
        avoid_for_skin_types=[],
        finish="light",
        tags=["控油", "修护", "提亮"],
        hero_ingredients=["niacinamide", "zinc pca", "beta glucan"],
        free_from_ingredients=["fragrance", "essential_oil"],
        notes="适合作为油皮和痘肌的日常维稳精华。",
    ),
    Product(
        id="ser-002",
        name="Deep Repair Ceramide Serum",
        brand="Eir Lab",
        category="serum",
        price=259,
        benefits=["barrier_support", "hydrating", "soothing"],
        suitable_skin_types=["dry", "sensitive", "combination"],
        avoid_for_skin_types=[],
        finish="rich",
        tags=["修护", "换季", "泛红"],
        hero_ingredients=["ceramide", "cholesterol", "panthenol"],
        free_from_ingredients=["fragrance"],
        notes="针对泛红、紧绷、屏障受损更友好。",
    ),
    Product(
        id="mois-001",
        name="Cloud Gel Moisturizer",
        brand="Pure Current",
        category="moisturizer",
        price=149,
        benefits=["hydrating", "lightweight", "anti_acne"],
        suitable_skin_types=["oily", "combination", "acne_prone"],
        avoid_for_skin_types=[],
        finish="gel",
        tags=["啫喱", "夏天", "清爽"],
        hero_ingredients=["glycerin", "panthenol", "ectoin"],
        free_from_ingredients=["fragrance"],
        notes="啫喱质地，适合夏天和易闷痘肤质。",
    ),
    Product(
        id="mois-002",
        name="Comfort Barrier Cream",
        brand="Atelo",
        category="moisturizer",
        price=189,
        benefits=["hydrating", "barrier_support", "soothing"],
        suitable_skin_types=["dry", "sensitive", "normal"],
        avoid_for_skin_types=["oily"],
        finish="cream",
        tags=["面霜", "维稳", "秋冬"],
        hero_ingredients=["ceramide", "shea butter", "panthenol"],
        free_from_ingredients=["alcohol_denat"],
        notes="偏滋润，更适合干皮和秋冬使用。",
    ),
    Product(
        id="base-001",
        name="Soft Matte Skin Tint",
        brand="Lumine",
        category="foundation",
        price=239,
        benefits=["light_coverage", "long_wear", "oil_control"],
        suitable_skin_types=["oily", "combination", "normal"],
        avoid_for_skin_types=["dry"],
        finish="matte",
        tags=["底妆", "通勤", "轻薄"],
        hero_ingredients=["silica", "niacinamide"],
        free_from_ingredients=["fragrance"],
        notes="更适合想要轻薄、通勤、偏雾面妆效的人群。",
    ),
    Product(
        id="base-002",
        name="Glow Cushion Foundation",
        brand="Mere",
        category="foundation",
        price=299,
        benefits=["medium_coverage", "glow", "hydrating"],
        suitable_skin_types=["dry", "normal", "sensitive"],
        avoid_for_skin_types=["acne_prone"],
        finish="glowy",
        tags=["光泽", "约会", "补妆方便"],
        hero_ingredients=["hyaluronic acid", "panthenol"],
        free_from_ingredients=["essential_oil"],
        notes="更偏光泽奶油肌，适合干皮或中性皮。",
    ),
    Product(
        id="lip-001",
        name="Velvet Blur Lip Mud",
        brand="Roue",
        category="lip",
        price=89,
        benefits=["long_wear", "soft_focus"],
        suitable_skin_types=["normal", "dry", "oily", "combination", "sensitive"],
        avoid_for_skin_types=[],
        finish="velvet",
        tags=["唇泥", "雾面", "显白"],
        hero_ingredients=["vitamin e"],
        free_from_ingredients=[],
        notes="雾面柔焦，适合日常和通勤妆。",
    ),
    Product(
        id="clean-001",
        name="Low pH Amino Cleanser",
        brand="DermaVeil",
        category="cleanser",
        price=99,
        benefits=["cleansing", "barrier_support", "daily"],
        suitable_skin_types=["sensitive", "dry", "combination", "oily", "acne_prone", "normal"],
        avoid_for_skin_types=[],
        finish="soft",
        tags=["氨基酸", "温和", "晨洁"],
        hero_ingredients=["amino acid surfactants", "panthenol"],
        free_from_ingredients=["sls"],
        notes="温和清洁，适合作为大部分肤质的基础洁面。",
    ),
]
